### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by lm913** [abhisheksoni27/codespell#3]
Running:
    OSX:       v10.12.5
    Node.js:  v8.2.1

`Fri Jul 21 2017

Sat Jul 22 2017
 Atom💻: undefined ✨
 Visual Studio Code💻: undefined ✨
(node:34737) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): undefined
(node:34737) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): undefined`

**Comment by abhisheksoni27** [comment]
Can you please try deleting `$HOME/.codespell` and running `codespell` again?

**Comment by lm913** [comment]
`$HOME/.codespell` does not exist. I installed codespell through `npm i -g codespell`, I've also uninstalled and reinstalled it

**Comment by lm913** [comment]
More CLI information

`(node:53617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by abhisheksoni27** [comment]
AFAIK, all promises have a catch clause in `index.js`. But, I'm looking into it. Thank you for providing more information.

**Comment by abhisheksoni27** [comment]
> // Errors thrown inside asynchronous functions will act like uncaught errors

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by abhisheksoni27** [comment]
@lm913 Hey! I just changed introduced major changes to the API. Can you reinstall and try again? :tada:

**Comment by lm913** [comment]
Gave it a reinstall and am now getting

`fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/********/.codespell/codespell-Sat-Jul-22-2017.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.readFileAsync (/Users/********/.nvm/versions/node/v8.2.1/lib/node_modules/codespell/promises/fs.js:4:15)
    at displayPast (/Users/********/.nvm/versions/node/v8.2.1/lib/node_modules/codespell/index.js:215:25)
    at Object.<anonymous> (/Users/********/.nvm/versions/node/v8.2.1/lib/node_modules/codespell/index.js:59:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

whether or not I use `codespell` or `sudo codespell`

it doesn't seem to create the directory structure :/

**Comment by lm913** [comment]
Maybe do a check to see if the folder exists and if it does then write to it otherwise make the directory first and then write to it

```
let storageFolder = home + '/.codespell' 
let fileName = `codespell-${date}.json`;

if (!window.cep.fs.stat(storageFolder).data.isDirectory()) {
    var result = window.cep.fs.makedir(storageFolder);

    // CODE GOES HERE
}
```

**Comment by abhisheksoni27** [comment]
How about:

```js
        try {
            data = fsOriginal.readFileSync(fileName);
            fileData = JSON.parse(String(data))
        } catch (readError) {
            if(readError) return;
        }
```

I was able to reproduce the issue locally (My bad, didn't check if it worked if the directory didn't exist.), and that, Sir, fixed it. :dagger: 

Changes landing soon.

**Comment by abhisheksoni27** [comment]
![](https://m.popkey.co/54972f/jZdem.gif)

Fixed! :tada:

**Comment by lm913** [comment]
It now creates the directory and the corresponding JSON file! :D

**Comment by abhisheksoni27** [comment]
Thanks for finding the bug, Sir. Closing the issue.
